import type { Tool } from "@/types";

const BRAND_TOOL_COLOR = "#1175ef";

export const tools: Tool[] = [
  { id: "merge", title: "Merge PDF", description: "Combine PDFs in the order you want with the easiest PDF merger available.", category: "organize", path: "/merge-pdf", color: BRAND_TOOL_COLOR },
  { id: "split", title: "Split PDF", description: "Separate one page or a whole set for easy conversion into independent PDF files.", category: "organize", path: "/split-pdf", color: BRAND_TOOL_COLOR },
  { id: "compress", title: "Compress PDF", description: "Reduce file size while optimizing for maximal PDF quality.", category: "optimize", path: "/compress-pdf", color: BRAND_TOOL_COLOR },
  { id: "pdf-to-word", title: "PDF to Word", description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.", category: "convert", path: "/pdf-to-word", color: BRAND_TOOL_COLOR },
  { id: "pdf-to-ppt", title: "PDF to PowerPoint", description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.", category: "convert", path: "/pdf-to-powerpoint", color: BRAND_TOOL_COLOR },
  { id: "pdf-to-excel", title: "PDF to Excel", description: "Pull data straight from PDFs into Excel spreadsheets.", category: "convert", path: "/pdf-to-excel", color: BRAND_TOOL_COLOR },
  { id: "word-to-pdf", title: "Word to PDF", description: "Make DOC and DOCX files easy to read by converting them to PDF.", category: "convert", path: "/word-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "ppt-to-pdf", title: "PowerPoint to PDF", description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.", category: "convert", path: "/powerpoint-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "excel-to-pdf", title: "Excel to PDF", description: "Make EXCEL spreadsheets easy to read by converting them to PDF.", category: "convert", path: "/excel-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "pdf-to-jpg", title: "PDF to JPG", description: "Convert each PDF page into a JPG or extract all images contained in a PDF.", category: "convert", path: "/pdf-to-jpg", color: BRAND_TOOL_COLOR },
  { id: "jpg-to-pdf", title: "JPG to PDF", description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.", category: "convert", path: "/jpg-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "png-to-pdf", title: "PNG to PDF", description: "Convert PNG and WEBP images to PDF with custom layout options.", category: "convert", path: "/png-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "image-to-pdf", title: "Image to PDF", description: "Convert JPG, PNG, WEBP, GIF, BMP, and TIFF images to PDF with custom layout options.", category: "convert", path: "/image-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "rotate", title: "Rotate PDF", description: "Rotate PDF pages by 90 degrees left or right.", category: "edit", path: "/rotate-pdf", color: BRAND_TOOL_COLOR },
  { id: "edit", title: "Edit PDF", description: "Add text, images, shapes or freehand annotations to a PDF document.", category: "edit", path: "/edit-pdf", color: BRAND_TOOL_COLOR },
  { id: "remove-pages", title: "Remove Pages", description: "Remove pages from a PDF document easily.", category: "organize", path: "/remove-pages", color: BRAND_TOOL_COLOR },
  { id: "watermark", title: "Add Watermark", description: "Add text or image watermark to your PDF files.", category: "edit", path: "/add-watermark", color: BRAND_TOOL_COLOR },
  { id: "page-numbers", title: "Add Page Numbers", description: "Add page numbers to your PDF files easily.", category: "edit", path: "/add-page-numbers", color: BRAND_TOOL_COLOR },
  { id: "unlock", title: "Unlock PDF", description: "Remove PDF password protection to unlock your PDF files.", category: "security", path: "/unlock-pdf", color: BRAND_TOOL_COLOR },
  { id: "protect", title: "Protect PDF", description: "Add password protection to your PDF files.", category: "security", path: "/protect-pdf", color: BRAND_TOOL_COLOR },
  { id: "organize", title: "Organize PDF", description: "Reorder, add, delete pages in your PDF document.", category: "organize", path: "/organize-pdf", color: BRAND_TOOL_COLOR },
  { id: "crop", title: "Crop PDF", description: "Crop pages in your PDF to get the perfect margins.", category: "edit", path: "/crop-pdf", color: BRAND_TOOL_COLOR },
  { id: "sign", title: "Sign PDF", description: "Add your signature to PDF documents easily.", category: "security", path: "/sign-pdf", color: BRAND_TOOL_COLOR },
  { id: "repair", title: "Repair PDF", description: "Repair damaged or corrupted PDF files.", category: "optimize", path: "/repair-pdf", color: BRAND_TOOL_COLOR },
  { id: "html-to-pdf", title: "HTML to PDF", description: "Convert HTML web pages to PDF files.", category: "convert", path: "/html-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "pdf-to-pdfa", title: "PDF to PDF/A", description: "Convert your PDF files to PDF/A format for long-term archiving.", category: "convert", path: "/pdf-to-pdfa", color: BRAND_TOOL_COLOR },
  { id: "redact", title: "Redact PDF", description: "Permanently remove sensitive information from your PDF.", category: "security", path: "/redact-pdf", color: BRAND_TOOL_COLOR },
  { id: "compare", title: "Compare PDF", description: "Compare two PDF files side by side to find differences.", category: "security", path: "/compare-pdf", color: BRAND_TOOL_COLOR },
  { id: "scan", title: "Scan to PDF", description: "Scan documents and convert them to PDF format.", category: "organize", path: "/scan-to-pdf", color: BRAND_TOOL_COLOR },
  { id: "ocr", title: "OCR PDF", description: "Convert scanned PDF documents into searchable text.", category: "optimize", path: "/ocr-pdf", color: BRAND_TOOL_COLOR },
  { id: "summarize", title: "AI Summarizer", description: "Summarize PDF documents using AI technology.", category: "intelligence", path: "/pdf-summarize", color: BRAND_TOOL_COLOR },
  { id: "translate", title: "Translate PDF", description: "Translate your PDF files into different languages.", category: "intelligence", path: "/translate-pdf", color: BRAND_TOOL_COLOR },
  { id: "forms", title: "PDF Forms", description: "Fill out and edit PDF forms easily.", category: "edit", path: "/pdf-forms", color: BRAND_TOOL_COLOR },
];
